### PR TITLE
Switch to FragmentManager.FragmentLifecycleCallbacks

### LINKED ISSUE #12: bug: cannot cleanup fragment in `onDestroyView()`
i am using this library with a `RecyclerView`, and i need to cleanup resources in `onDestroyView()`.
in order to prevent a memory leak i need to do this:
```
override fun onDestroyView() {
        binding.recyclerView.adapter = null
        super.onDestroyView()
    }
```

but i get an error: `java.lang.IllegalStateException: Should not attempt to get bindings when Fragment views are destroyed.`

i did a quick google search and found [this](https://proandroiddev.com/make-android-view-binding-great-with-kotlin-b71dd9c87719) article where this very problem is described and solved in [this section](https://proandroiddev.com/make-android-view-binding-great-with-kotlin-b71dd9c87719#e8bc) (link may not work 100%, the section is "Something went wrong").

please add this to your library :)

### PR DESCRIPTION
**Pull request by bleeding182**
Making the switch to Fragment LCCs should fix #12, since the view lifecycle destroy event gets called _before_ `onDestroyView`, but only `onFragmentViewDestroyed` gets called _after_. (As a side effect we can also drop the livedata dependency)

(Sidenote: I have not tested this in an actual project yet, will try to do so next week)

Curious what you think

### CODE REVIEW

**Comment by Zhuinden** [comment]
I think this works, theoretically, as long as the user guarantees to get the binding in `onViewCreated` first, which they usually do.

In theory, it is possible to subscribe for `onDestroyView` from `onViewCreated` via the Lifecycle, but I know a lot of people don't seem to think of that option. :thinking: I blame it on it not being really a thing in `lifecycle-ktx`, theoretically they could just expose a `viewLifecycleOwner.onDestroy {}` and it would actually work.

Also see https://github.com/Zhuinden/fragmentviewbindingdelegate-kt/issues/12#issuecomment-812906086

**Comment by bleeding182** [comment]
`.observeOnDestroy` (as per your comment) is an interesting approach (and I actually did not think of that, so TIL :) ), albeit it could still lead to a crash in some (very edge&mdash;I guess) cases, since we must rely on that lifecycle observer to be called _before_ the lifecycle observer in the delegate, or the binding will already be `null` at that point...causing an exception.

> I think this works, theoretically, as long as the user guarantees to get the binding in onViewCreated first, which they usually do.

Could you elaborate on this? I don't see it.

Due to the lazy implementation the binding can/will be created in any valid state between [viewCreated -> viewDestroyed] (both inclusive) and it will be registered for removal in fragmentViewDestroyed, with the added benefit that there is no chance for any race condition as mentioned above, since the fragment lifecycle callbacks happen after the view is actually gone, the viewLifecycle is destroyed, and all lifecycle observers are done (and calling it outside of that lifecycle will crash (as expected))

**Comment by JanuszHain** [comment]
Thanks for the proposed change. It indeed works better, as Fragment's `onDestroyView` is not a problem anymore. One thing that could also be changed: `check(viewLifecycle.currentState.isAtLeast(Lifecycle.State.INITIALIZED))`. If the binding wasn't initialized before `onDestroyView`, but we have to use binding in this method, the app will crash, as Lifecycle state is `DESTROYED` (lower number than `INITIALIZED`). My check is simplier - checking if Fragment's view is null or not

**Comment by Zhuinden** [comment]
I picked this approach instead https://github.com/Zhuinden/fragmentviewbindingdelegate-kt/issues/12#issuecomment-1221558169 but thanks for the contribution and hope your fork worked well for you 😉

**Pull request closed without merging**
